### ISSUE TITLE
[FEATURE] Finding details flyout - clicking on rule name should trigger Rule details flyout

### ISSUE THREAD

**Issue by phestecAMZN** [opensearch-project/security-analytics-dashboards-plugin#124]
**Is your feature request related to a problem?**
Currently this action navigates the user to the general Rules page.

**What solution would you like?**
Present the Rule details flyout to the user without navigating anywhere

**What alternatives have you considered?**

**Do you have any additional context?**

**Comment by djindjic** [comment]
@getsaurabh02 @amsiglan 
### Initially state
Clicking on rule name was opening list of all rules
###
In order to reuse `<RuleViewerFlyout>` component it should be able to drop-in not only on Findings page, but also on Alerts. On video below you can see how it looks at the moment in my local (with fake rule data).

https://user-images.githubusercontent.com/1564068/207426202-4cffb9d4-6120-4a11-8748-c05ce431246f.mov

### Here was needed to:
- align Rule flyout header to looks the same as Alert and Finding details
- fix one existing runtime error on alert flyput opening<img width="592" alt="image" src="https://user-images.githubusercontent.com/1564068/207427480-680f509c-a493-4751-b9d3-65148b587932.png">

There is also "back button" functionality in case of flyouts opening one over another, which I personally think is overhead (let me know if we could agree on it so close X button would always behave as back arrow `<` button at the moment and `<` could be removed?

I lost some time on thinking if we can have only one template for all flyouts in plugin, but it seems complicate to be done in this context.

### Remain work
I was doing above layouting with mocked Rule details (from Rules page). Getting Rule details on Findings and Alerting page is left to be done in some proper way that I will discuss with @amsiglan. If there is no already data needed, I would like to not pass too many props and services around. Trying also to contribute more on general code organization/architecture with some feedback, hope it could be helpful too.
